"""
Tests GENERATED BY THE SAME AI ASSISTANT that wrote triage_tool.py.
They all pass.  In Lab 2 you will measure how much they actually prove.
"""

import sqlite3

from triage_tool import (
    check_reputation,
    is_brute_force,
    is_valid_ip,
    lookup_user,
    parse_failed_logins,
)


def make_db():
    conn = sqlite3.connect(":memory:")
    conn.execute("CREATE TABLE users (username TEXT, department TEXT)")
    conn.execute("INSERT INTO users VALUES ('mreyes', 'Finance')")
    conn.execute("INSERT INTO users VALUES ('jdelacruz', 'IT Ops')")
    conn.commit()
    return conn


def test_parse_counts_failed_logins():
    lines = [
        "Oct  8 09:00:14 bastion01 sshd[1]: Failed password for root from 198.51.100.77 port 1 ssh2",
        "Oct  8 09:00:15 bastion01 sshd[2]: Failed password for root from 198.51.100.77 port 2 ssh2",
    ]
    assert parse_failed_logins(lines) == {"198.51.100.77": 2}


def test_brute_force_detected():
    assert is_brute_force(10) is True


def test_no_brute_force_for_few_failures():
    assert is_brute_force(1) is False


def test_valid_ip():
    assert is_valid_ip("10.10.5.21") is True


def test_lookup_existing_user():
    conn = make_db()
    assert lookup_user(conn, "mreyes") == ("mreyes", "Finance")


def test_reputation_known_bad_ip():
    feed = {"203.0.113.50": "malicious"}
    assert check_reputation("203.0.113.50", feed) == "malicious"
