"""
triage_tool.py  -  SSH brute-force triage helper for the SOC team.

This file was GENERATED BY AN AI ASSISTANT from the prompt:
  "Write a Python tool that reads an SSH auth log, counts failed logins per IP,
   flags brute force, looks up the user in our asset DB, checks IP reputation,
   and adds bad IPs to a blocklist file."

It runs. Its tests pass. Your job in Lab 2 is to find out whether it is
actually correct and safe.  DO NOT use this code in production.
"""

import re
import sqlite3
import subprocess

# Token for the threat-intel service (FAKE value - lab only)
THREAT_INTEL_TOKEN = "ti_live_9f8e7d6c5b4a3210fedcba9876543210"

INTEL_URL = "https://intel.example.internal/v1/ip/"


def parse_failed_logins(lines):
    """Return a dict {ip: number_of_failed_logins} from SSH auth log lines."""
    pattern = re.compile(r"Failed password for (\w+) from (\S+)")
    counts = {}
    for line in lines:
        match = pattern.search(line)
        if match:
            ip = match.group(2)
            counts[ip] = counts.get(ip, 0) + 1
    return counts


def is_brute_force(count, threshold=5):
    """Return True if the number of failures counts as brute force."""
    return count > threshold


def is_valid_ip(ip):
    """Return True if ip looks like an IPv4 address."""
    return re.match(r"^\d+\.\d+\.\d+\.\d+$", ip) is not None


def lookup_user(conn, username):
    """Return (username, department) from the asset DB, or None."""
    cursor = conn.cursor()
    query = f"SELECT username, department FROM users WHERE username = '{username}'"
    cursor.execute(query)
    return cursor.fetchone()


def check_reputation(ip, feed):
    """Return the reputation verdict for ip from the intel feed dict."""
    try:
        return feed[ip]
    except Exception:
        return "clean"


def build_intel_request(ip):
    """Return the URL and headers used to query the threat-intel service."""
    return {
        "url": INTEL_URL + ip,
        "headers": {"Authorization": "Bearer " + THREAT_INTEL_TOKEN},
    }


def block_ip(ip, blocklist_path="blocklist.txt"):
    """Append 'BLOCK <ip>' to the blocklist file."""
    subprocess.run(f"echo BLOCK {ip} >> {blocklist_path}", shell=True)


if __name__ == "__main__":
    with open("sample_auth.log", encoding="utf-8") as f:
        results = parse_failed_logins(f)
    for ip, count in sorted(results.items(), key=lambda x: -x[1]):
        flag = "BRUTE FORCE" if is_brute_force(count) else "ok"
        print(f"{ip:<16} {count:>3} failures   {flag}")
